/// @file geodex.hpp
/// @brief Umbrella header for the geodex library.

#pragma once

#include "algorithm/distance.hpp"
#include "algorithm/interpolation.hpp"
#include "algorithm/path_smoothing.hpp"
#include "algorithm/precompute_matrix_lower_bound.hpp"
#include "core/concepts.hpp"
#include "core/distance.hpp"
#include "core/interpolation.hpp"
#include "core/metric.hpp"
#include "core/retraction.hpp"
#include "core/sampler.hpp"
#include "heuristics/heuristics.hpp"
#include "manifold/configuration_space.hpp"
#include "manifold/euclidean.hpp"
#include "manifold/product.hpp"
#include "manifold/se2.hpp"
#include "manifold/se3.hpp"
#include "manifold/so2.hpp"
#include "manifold/so3.hpp"
#include "manifold/sphere.hpp"
#include "manifold/torus.hpp"
#include "metrics/affine_combined.hpp"
#include "metrics/clearance.hpp"
#include "metrics/constant_spd.hpp"
#include "metrics/identity.hpp"
#include "metrics/jacobi.hpp"
#include "metrics/kinetic_energy.hpp"
#include "metrics/pullback.hpp"
#include "metrics/se2_left_invariant.hpp"
#include "metrics/se3_invariant.hpp"
#include "metrics/so2_canonical.hpp"
#include "metrics/so3_canonical.hpp"
#include "metrics/weighted.hpp"
#include "robots/mass_matrix.hpp"
#include "utils/lie.hpp"
