/// @file test_vamp_pr2.cpp
/// @brief Tests for the fixed-base dual-arm PR2 VAMP specialization.

#include <algorithm>
#include <array>
#include <memory>
#include <string>

#include <gtest/gtest.h>
#include <ompl/base/SpaceInformation.h>
#include <ompl/base/spaces/RealVectorStateSpace.h>

#include "geodex/integration/vamp/registry.hpp"

namespace {

constexpr const char* kFixturesDir = GEODEX_TEST_FIXTURES_DIR;

auto fixture_path(const std::string& relative) -> std::string {
  return std::string(kFixturesDir) + "/" + relative;
}

// Fixed-base PR2 dual-arm joint order generated by cricket:
//   left arm first, then right arm, matching data/robots/pr2/robot.yaml.
constexpr std::array<double, 14> kStartPose{0.9117,  0.4768,  1.5995,  -1.4905, 0.0992,
                                            -0.2865, 1.4881,  -0.9117, 0.4768,  -1.5995,
                                            -1.4905, -0.0992, -0.2865, -1.4881};

constexpr std::array<double, 14> kGoalPose{0.9275,  -0.3114, 1.7232,  -1.7349, 0.0992,
                                           -0.2865, 1.4881,  -0.9275, -0.3114, -1.7232,
                                           -1.7349, -0.0992, -0.2865, -1.4881};

constexpr std::array<double, 14> kNearStartPose{0.9217,  0.4568,  1.5995,  -1.5005, 0.0992,
                                                -0.2865, 1.4881,  -0.9217, 0.4568,  -1.5995,
                                                -1.5005, -0.0992, -0.2865, -1.4881};

auto make_pr2_space_information() -> ompl::base::SpaceInformationPtr {
  auto space = std::make_shared<ompl::base::RealVectorStateSpace>(14);
  ompl::base::RealVectorBounds bounds(14);
  bounds.setLow(-3.14159);
  bounds.setHigh(3.14159);
  space->setBounds(bounds);
  return std::make_shared<ompl::base::SpaceInformation>(space);
}

auto make_pr2_state(const ompl::base::SpaceInformationPtr& si, const std::array<double, 14>& q)
    -> ompl::base::State* {
  auto* state = si->allocState();
  auto* rv = state->as<ompl::base::RealVectorStateSpace::StateType>();
  for (int i = 0; i < 14; ++i) rv->values[i] = q[i];
  return state;
}

}  // namespace

namespace vamp_int = geodex::integration::vamp;

TEST(VampPr2, RegistersInRegistry) {
  const auto names = vamp_int::registered_robots();
  EXPECT_NE(std::find(names.begin(), names.end(), "pr2"), names.end());
}

TEST(VampPr2, MakeCheckerReturnsNonNull) {
  auto env = vamp_int::load_scene(fixture_path("vamp/pr2/empty.yaml"));
  auto checker = vamp_int::make_vamp_checker("pr2", env);
  ASSERT_NE(checker, nullptr);
}

TEST(VampPr2, WrongDimReturnsFalse) {
  auto env = vamp_int::load_scene(fixture_path("vamp/pr2/empty.yaml"));
  auto checker = vamp_int::make_vamp_checker("pr2", env);
  EXPECT_FALSE(checker->is_valid(kStartPose.data(), 13));
  EXPECT_FALSE(checker->is_valid(kStartPose.data(), 15));
}

TEST(VampPr2, EmptySceneAcceptsRequestPoses) {
  auto env = vamp_int::load_scene(fixture_path("vamp/pr2/empty.yaml"));
  auto checker = vamp_int::make_vamp_checker("pr2", env);
  EXPECT_TRUE(checker->is_valid(kStartPose.data(), 14));
  EXPECT_TRUE(checker->is_valid(kNearStartPose.data(), 14));
  EXPECT_TRUE(checker->is_valid(kGoalPose.data(), 14));
}

TEST(VampPr2, EnclosureRejectsStartPose) {
  auto env = vamp_int::load_scene(fixture_path("vamp/pr2/enclosure.yaml"));
  auto checker = vamp_int::make_vamp_checker("pr2", env);
  EXPECT_FALSE(checker->is_valid(kStartPose.data(), 14));
}

TEST(VampPr2, MotionValidatorAcceptsClearMotion) {
  auto si = make_pr2_space_information();
  auto env = vamp_int::load_scene(fixture_path("vamp/pr2/empty.yaml"));
  auto validator = vamp_int::make_vamp_motion_validator("pr2", si, env);
  ASSERT_NE(validator, nullptr);

  auto* s1 = make_pr2_state(si, kStartPose);
  auto* s2 = make_pr2_state(si, kNearStartPose);
  EXPECT_TRUE(validator->checkMotion(s1, s2));
  si->freeState(s1);
  si->freeState(s2);
}

TEST(VampPr2, MotionValidatorRejectsBlockedMotion) {
  auto si = make_pr2_space_information();
  auto env = vamp_int::load_scene(fixture_path("vamp/pr2/enclosure.yaml"));
  auto validator = vamp_int::make_vamp_motion_validator("pr2", si, env);
  auto* s1 = make_pr2_state(si, kStartPose);
  auto* s2 = make_pr2_state(si, kNearStartPose);
  EXPECT_FALSE(validator->checkMotion(s1, s2));
  si->freeState(s1);
  si->freeState(s2);
}
