#!/usr/bin/env python3
"""Post-process a CRBA source that CppAD::CG generated.

    python3 scripts/robotgen/post_process_sincos_simd.py <input.cpp> <output.cpp> <robot_name>

It moves the `sin(x[i])` and `cos(x[i])` calls of `<robot>_crba_forward_zero` into a prelude
at the top of the function. On macOS, the prelude calls Accelerate's `vvsincos`. Elsewhere,
it runs one sine loop and one cosine loop, which GCC vectorizes with glibc's libmvec on
Linux x86_64. The script also
replaces the eps-sized constants of the CppAD::CG trace with zero and gives the CppAD::CG
helper functions internal linkage. A missing pattern is an error.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def internalize_aux_functions(src: str, keep_external: set[str]) -> str:
    """Give CppAD::CG helper definitions internal linkage inside extern "C"."""
    extern_block_re = re.compile(
        r'(extern "C" \{\n)([\s\S]*?)(\n\}  // extern "C"\n)'
    )
    block_match = extern_block_re.search(src)
    if not block_match:
        sys.exit('error: could not locate the wrapping extern "C" block')
    block_head, block_body, block_tail = block_match.groups()

    fndef_re = re.compile(
        r'^((?:[A-Za-z_][A-Za-z0-9_]*\s+){1,2}[*\s]*'
        r'([A-Za-z_][A-Za-z0-9_]*)\s*\([^)]*\)\s*\{)',
        re.MULTILINE,
    )

    def maybe_static(m: re.Match) -> str:
        if m.group(1).startswith("static ") or m.group(2) in keep_external:
            return m.group(1)
        return f"static {m.group(1)}"

    block_body = fndef_re.sub(maybe_static, block_body)
    return (
        src[: block_match.start()]
        + block_head
        + block_body
        + block_tail
        + src[block_match.end() :]
    )


def post_process(input_path: Path, output_path: Path, robot_name: str) -> None:
    src = input_path.read_text()
    fwd_name = f"{robot_name}_crba_forward_zero"

    # Find the body of forward_zero. Only that body is patched.
    fn_re = re.compile(
        r"(void\s+" + re.escape(fwd_name) + r"\s*\([^)]*\)\s*\{)([\s\S]*?)(\n\}\s*\n)",
        re.MULTILINE,
    )
    m = fn_re.search(src)
    if not m:
        sys.exit(f"error: could not locate function body for {fwd_name}")
    head, body, tail = m.group(1), m.group(2), m.group(3)

    # Match every `v[A] = cos(x[i]);` and `v[A] = sin(x[i]);` line and capture A and i.
    trig_re = re.compile(
        r"^(\s*)(v\[(\d+)\])\s*=\s*(cos|sin)\(x\[(\d+)\]\)\s*;\s*$",
        re.MULTILINE,
    )

    # Collect every call and the angles it reads.
    calls = list(trig_re.finditer(body))
    if not calls:
        sys.exit("error: found no cos(x[i])/sin(x[i]) lines in forward_zero")

    angles_used = sorted({int(m.group(5)) for m in calls})
    n_angles = len(angles_used)
    print(
        f"found {len(calls)} trig calls touching {n_angles} angle indices: "
        f"{angles_used}",
        file=sys.stderr,
    )

    # Pad to the next multiple of 4 (AVX2 lane width).
    padded = ((n_angles + 3) // 4) * 4
    angle_to_buf_idx = {ang: i for i, ang in enumerate(angles_used)}

    # Replace `v[A] = cos(x[i]);` with `v[A] = _trig_cos[k];`, and the same for sine.
    def replace_call(m: re.Match) -> str:
        indent, lhs, _lhs_idx, fn, ang_idx = m.group(1), m.group(2), m.group(3), m.group(4), m.group(5)
        buf = "_trig_cos" if fn == "cos" else "_trig_sin"
        bi = angle_to_buf_idx[int(ang_idx)]
        return f"{indent}{lhs} = {buf}[{bi}];  // hoisted: was {fn}(x[{ang_idx}])"

    patched_body = trig_re.sub(replace_call, body)

    # The prelude gathers the angles into an aligned buffer and runs the two loops.
    gather_lines = "\n".join(
        f"   _trig_in[{i}] = x[{ang}];" for i, ang in enumerate(angles_used)
    )
    pad_lines = "\n".join(
        f"   _trig_in[{i}] = 0.0;" for i in range(n_angles, padded)
    )
    prelude = (
        f"\n   // ---- vectorized-trig prelude (auto-generated by post_process_sincos_simd.py) ----\n"
        f"   alignas(32) double _trig_in [{padded}];\n"
        f"   alignas(32) double _trig_sin[{padded}];\n"
        f"   alignas(32) double _trig_cos[{padded}];\n"
        f"{gather_lines}\n"
        + (pad_lines + "\n" if pad_lines else "")
        + f"#if defined(__APPLE__)\n"
        f"   {{ int _n = {padded}; vvsincos(_trig_sin, _trig_cos, _trig_in, &_n); }}\n"
        f"#else\n"
        f"   for (int _i = 0; _i < {padded}; ++_i) _trig_sin[_i] = sin(_trig_in[_i]);\n"
        f"   for (int _i = 0; _i < {padded}; ++_i) _trig_cos[_i] = cos(_trig_in[_i]);\n"
        f"#endif\n"
        f"   // ---- end prelude ----\n"
    )

    # Insert the prelude right after the `double v[N];` declaration near the top.
    decl_re = re.compile(r"(\n\s*double\s+v\[\d+\];\s*\n)")
    if not decl_re.search(patched_body):
        sys.exit("error: could not find `double v[N];` declaration to anchor prelude")
    patched_body = decl_re.sub(lambda m: m.group(1) + prelude, patched_body, count=1)

    new_src = (
        src[: m.start()]
        + head
        + patched_body
        + tail
        + src[m.end() :]
    )

    # Give the CppAD::CG helpers internal linkage. Every robot source defines helpers with the
    # same names. forward_zero keeps external linkage.
    new_src = internalize_aux_functions(new_src, {fwd_name})

    # Replace the eps-sized constants of the CppAD::CG trace with zero.
    NOISE_CONSTS = (
        "2.22044604925031e-16",  # DBL_EPSILON, by far the most common
        "4.93038065763132e-32",  # ~ DBL_EPSILON^2
        "4.55369075780254e-18",
        "3.12638803734444e-19",
    )
    noise_count_before = sum(new_src.count(c) for c in NOISE_CONSTS)
    for c in NOISE_CONSTS:
        new_src = new_src.replace(c, "0.0")
    noise_count_after = sum(new_src.count(c) for c in NOISE_CONSTS)
    print(
        f"dropped {noise_count_before - noise_count_after} noise terms "
        f"(eps-magnitude constants → 0.0)",
        file=sys.stderr,
    )

    # Include Accelerate for vvsincos after `#include <math.h>`, once.
    accel_block = (
        "#include <math.h>\n"
        "#if defined(__APPLE__)\n"
        "#  include <Accelerate/Accelerate.h>  /* vvsincos */\n"
        "#endif\n"
    )
    if "Accelerate/Accelerate.h" not in new_src:
        if "#include <math.h>" not in new_src:
            sys.exit("error: could not locate `#include <math.h>` to anchor Accelerate include")
        new_src = new_src.replace("#include <math.h>\n", accel_block, 1)

    # Name both generators in the file header.
    watermark_replacement = (
        "// AUTO-GENERATED by scripts/robotgen/pinocchio_codegen and scripts/robotgen/post_process_sincos_simd.py.\n"
        "// The post-processing hoists the sin and cos calls into a vectorized prelude, Apple\n"
        "// Accelerate `vvsincos` on macOS and libmvec on Linux x86_64 with a scalar fallback\n"
        "// elsewhere, and zeroes the eps-magnitude residuals of the CppAD::CG trace.\n"
        "// DO NOT EDIT."
    )

    new_src = new_src.replace(
        "// AUTO-GENERATED by scripts/robotgen/pinocchio_codegen. DO NOT EDIT.",
        watermark_replacement,
        1,
    )
    output_path.write_text(new_src)
    print(f"wrote {output_path} ({len(new_src)} bytes)", file=sys.stderr)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("input", type=Path, help="Generated <robot>_crba.cpp")
    p.add_argument("output", type=Path, help="Destination path (may equal input for in-place)")
    p.add_argument("robot_name", help="Robot identifier embedded in the symbol names (e.g. panda)")
    args = p.parse_args()
    post_process(args.input, args.output, args.robot_name)


if __name__ == "__main__":
    main()
