/// @file scripts/robotgen/precompute_robot_bound.cpp
/// @brief Writes the Loewner lower bound of a robot's mass matrix.
///
///   precompute_robot_bound <robot_name> <out_dir>
///
/// `precompute_matrix_lower_bound` shapes a constant matrix `L` under `M(q)` on the joint
/// box, and `certify::certify` proves a scale `s` for each independent block of the mass
/// matrix. The tool writes `M_lower = s L` to <out_dir>/<robot_name>_bound.hpp as the
/// row-major upper triangle. When the proof does not finish, each block's scale is its
/// sampled minimum reduced by the relative margin `kSampledMargin`, and the header marks the
/// bound as not proved.
///
/// The tool needs `GEODEX_ENABLE_ROBOT_REGEN`. Built without `-march=native` and fast math,
/// it writes the same digits on every host.

#include <cmath>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <sstream>
#include <string>
#include <utility>

#include <Eigen/Core>

#include "crba_templates.hpp"
#include "geodex/algorithm/precompute_matrix_lower_bound.hpp"
#include "geodex/manifold/configuration_space.hpp"
#include "geodex/manifold/euclidean.hpp"
#include "geodex/metrics/kinetic_energy.hpp"
#include "geodex/robots/mass_matrix.hpp"

namespace fs = std::filesystem;

namespace {

using geodex::algorithm::PrecomputeMatrixLowerBoundSettings;
using geodex::robots::certify::CertifyResult;

std::string list(const std::vector<int>& v) {
  std::ostringstream o;
  for (std::size_t i = 0; i < v.size(); ++i) o << (i ? " " : "") << v[i];
  return o.str();
}

/// Margin below the sampled minimum of a block whose proof did not finish.
constexpr double kSampledMargin = 3e-2;

/// Emit the bound as a self-contained constexpr header
/// (row-major upper triangle, 17-digit doubles, `geodex::robots::generated` namespace).
void write_bound_header(const fs::path& path, const std::string& name, int nq,
                        const CertifyResult& r, const PrecomputeMatrixLowerBoundSettings& s) {
  const int upper_count = nq * (nq + 1) / 2;
  double certificate = std::numeric_limits<double>::infinity();
  for (const auto& b : r.blocks) {
    certificate = std::min(certificate, (r.proved ? b.proved_min : b.sampled_min) / b.scale);
  }

  std::ofstream out(path);
  out.precision(17);
  out << "// AUTO-GENERATED by scripts/robotgen/precompute_robot_bound. DO NOT EDIT.\n"
      << "// Loewner lower bound M_lower of the CRBA kinetic-energy metric g(q) = M(q).\n"
      << (r.proved
              ? "// M(q) >= M_lower for every q in [lower_limit, upper_limit], proved by interval\n"
                "// branch and bound over the generated CRBA expression (scripts/robotgen/crba_certify.hpp).\n"
              : "// Not proved. M_lower is the smallest lambda of a sampled search and a pattern\n"
                "// search, less the margin below, times the shaped matrix L.\n")
      << "// Feeds the admissible heuristic geodex::heuristics::MatrixLowerBound via\n"
      << "// geodex::robots::MassLowerBound<R>.\n"
      << "//\n"
      << (r.proved ? "// certificate = proved lower bound of lambda_min(M_lower^-1 M(q)) over the box = "
                   : "// certificate = smallest sampled lambda_min(M_lower^-1 M(q)) over the box = ")
      << certificate << "\n"
      << "// margin below the smallest sampled lambda = "
      << (r.proved ? r.margin : kSampledMargin)
      << ", held coordinates (M does not depend on them) = [" << list(r.held) << "]\n"
      << "// shape: precompute_matrix_lower_bound seed = " << s.seed << ", tol = " << s.tol
      << ", max_outer = " << s.max_outer << "; search seed = 42\n"
      << "// Regenerate with scripts/robotgen/generate.sh <robot>.\n"
      << "//\n"
      << "// Layout (row-major upper triangle of the symmetric Nv x Nv M_lower):\n"
      << "//   m[0] = M(0,0); m[1..Nv-1] = M(0,1..Nv-1); m[Nv] = M(1,1); ...\n"
      << "\n#pragma once\n\n"
      << "namespace geodex::robots::generated {\n"
      << "constexpr int " << name << "_lower_bound_count = " << upper_count << ";\n"
      // A written header always holds a finished bound, and `converged` is true.
      << "constexpr bool " << name << "_mass_lower_bound_converged = true;\n"
      << "constexpr bool " << name << "_mass_lower_bound_proved = " << (r.proved ? "true" : "false")
      << ";\n"
      << "constexpr double " << name << "_mass_lower_bound_certificate = " << certificate
      << ";\n"
      << "constexpr double " << name << "_mass_lower_bound[" << upper_count << "] = {";

  bool first = true;
  for (int i = 0; i < nq; ++i) {
    for (int j = i; j < nq; ++j) {
      out << (first ? "" : ", ") << r.M_lower(i, j);
      first = false;
    }
  }

  out << "};\n"
      << "}  // namespace geodex::robots::generated\n";
}

/// Shape a lower bound for robot @p R, prove it on the joint box, and write it.
template <geodex::robots::Robot R>
int bake(const std::string& name, const fs::path& out_dir) {
  using MM = geodex::robots::MassMatrix<R>;
  constexpr int Nq = MM::Nq;

  MM mm;
  const auto [lo_fixed, hi_fixed] = MM::joint_limits();
  const Eigen::VectorXd lo = lo_fixed;
  const Eigen::VectorXd hi = hi_fixed;

  geodex::Euclidean<Nq> base;
  base.set_sampling_bounds(lo, hi);
  geodex::KineticEnergyMetric<MM> metric{std::move(mm)};
  geodex::ConfigurationSpace<geodex::Euclidean<Nq>, geodex::KineticEnergyMetric<MM>> manifold{
      std::move(base), std::move(metric)};

  PrecomputeMatrixLowerBoundSettings settings;
  std::cerr << "[bound:" << name << "] shaping Loewner lower bound (dim=" << Nq << ")...\n";
  const auto shaped = geodex::algorithm::precompute_matrix_lower_bound(manifold, settings);
  std::cerr << "[bound:" << name << "] shaped: last-descent minimum "
            << shaped.lambda_min_certificate << " iterations=" << shaped.n_outer_iters
            << " evals=" << shaped.n_metric_evals << " elapsed_ms=" << shaped.elapsed_ms << "\n";

  const Eigen::MatrixXd L = shaped.M_lower;
  auto proof = geodex::robots::certify::certify<R>(L);
  if (!proof.proved) {
    proof.M_lower = L;
    for (auto& b : proof.blocks) {
      b.scale = std::floor(b.sampled_min * (1.0 - kSampledMargin) * 1e6) / 1e6;
      for (int i : b.coordinates) {
        for (int j : b.coordinates) proof.M_lower(i, j) = b.scale * L(i, j);
      }
    }
  }
  for (const auto& b : proof.blocks) {
    std::cerr << "[bound:" << name << "] block [" << list(b.coordinates) << "] scale " << b.scale
              << " sampled " << b.sampled_min << " proved " << b.proved_min << " boxes "
              << b.boxes << "\n";
  }
  std::cerr << "[bound:" << name << "] "
            << (proof.proved ? "proved at margin " : "not proved, sampled margin ")
            << (proof.proved ? proof.margin : kSampledMargin) << " in " << proof.seconds
            << " s, " << proof.samples << " sampled evaluations\n";

  const fs::path out = out_dir / (name + "_bound.hpp");
  write_bound_header(out, name, Nq, proof, settings);
  std::cerr << "[bound:" << name << "] wrote " << out << "\n";
  return 0;
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != 3) {
    std::cerr << "Usage: " << argv[0] << " <robot_name> <out_dir>\n";
    return 1;
  }
  const std::string name = argv[1];
  const fs::path out_dir = argv[2];
  fs::create_directories(out_dir);

  using geodex::robots::Robot;
  // GEODEX_ROBOT_BOUND_DISPATCH_BEGIN
  if (name == "baxter") return bake<Robot::Baxter>(name, out_dir);
  if (name == "fr3_gripper") return bake<Robot::Fr3Gripper>(name, out_dir);
  if (name == "husky_ur5e") return bake<Robot::HuskyUr5e>(name, out_dir);
  if (name == "panda") return bake<Robot::Panda>(name, out_dir);
  if (name == "pr2") return bake<Robot::Pr2>(name, out_dir);
  if (name == "ridgeback_ur5e") return bake<Robot::RidgebackUr5e>(name, out_dir);
  if (name == "stretch3") return bake<Robot::Stretch3>(name, out_dir);
  if (name == "stretch4") return bake<Robot::Stretch4>(name, out_dir);
  if (name == "ur5") return bake<Robot::Ur5>(name, out_dir);
  // GEODEX_ROBOT_BOUND_DISPATCH_END

  std::cerr << "unknown robot '" << name << "' (no MassMatrix<Robot> specialization)\n";
  return 1;
}
