name: wheels

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags: ["v*"]

jobs:
  build_wheels:
    name: ${{ matrix.os }} ${{ matrix.archs }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, archs: x86_64 }
          - { os: ubuntu-24.04-arm, archs: aarch64 }
          - { os: macos-14, archs: arm64 }
          - { os: macos-13, archs: x86_64 }
          - { os: windows-latest, archs: AMD64 }
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v3.0
        env:
          CIBW_ARCHS: ${{ matrix.archs }}
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.archs }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
